name: news
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.4.1
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  firebase_analytics: ^10.0.3
  sqflite: ^2.2.2
  path_provider: ^2.0.11
  path: ^1.8.2
  share_plus: ^6.3.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.11.0
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0
  firebase_storage: ^11.0.10
  url_launcher: ^6.1.7
  file_picker: ^5.2.5
  flutter_svg: ^1.1.6
  scroll_page_view: ^1.0.2
  google_fonts: ^4.0.1
  onboarding: ^3.1.0
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
